// Deterministic parity fixture generated by the actual LIFNetwork implementation.
// Keep setup through public LIFNetwork operations: direct typed-array mutation does
// not update lif.js's event-driven awake list.  The explicit wake below is required
// because this fixture deliberately seeds an above-threshold membrane voltage.
import { LIFNetwork } from "../../fly-brain-main/src/lif.js";

const brain = new LIFNetwork(
  3,
  new Uint32Array([0, 1, 2, 2]),
  new Uint32Array([1, 2]),
  new Uint16Array([5, 5]),
  new Uint8Array([1, 2, 1]),
  { dt: .5, vRest: -52, vThresh: -45, vReset: -52, tauM: 20,
    tauSyn: 5, tRef: 2.2, delay: 1.8, wSyn: 1, minSyn: 5,
    adaptInc: 0, depU: 0 }
);

brain.v[0] = -44;
brain.wake(0);
const output = [];
for (let timestep = 0; timestep < 7; timestep++) {
  const spikes = brain.step();
  output.push({
    timestep,
    v: [...brain.v], e: [...brain.gE], i: [...brain.gI],
    r: [...brain.refr], s: [...spikes], c: [...brain.spikeCount],
    ring: brain.ring.map(slot => [...slot]), head: brain.head,
  });
}
console.log(JSON.stringify(output));
